# Default configuration for berth allocation with shore power

# Environment configuration
environment:
  berth_length: 2000  # Total berth length in meters
  planning_horizon: 7  # Planning horizon in days
  max_vessels: 20  # Maximum number of vessels per episode
  safe_distance: 20  # Minimum safe distance between vessels (m)
  max_wait_time: 48.0  # Maximum waiting time (hours)
  target_utilization: 0.7  # Target berth utilization ratio

  # Shore power configuration
  shore_power:
    segments:
      - start: 0
        end: 400
        capacity: 5000  # kW
      - start: 400
        end: 800
        capacity: 5000
      - start: 800
        end: 1200
        capacity: 5000
      - start: 1200
        end: 1600
        capacity: 5000
      - start: 1600
        end: 2000
        capacity: 5000

    emission_factor_ship: 2500  # kg CO2 per MWh (ship auxiliary engine)
    emission_factor_shore: 800  # kg CO2 per MWh (shore power)

  # Reward weights
  rewards:
    c1: 10.0   # Base positive reward
    c2: 5.0    # Waiting time penalty
    c3: 8.0    # Carbon emission penalty
    c4: 6.0    # Shore power usage bonus
    c5: 4.0    # Berth utilization reward
    c6: 3.0    # Spacing reward
    c7: 0.0    # Reserved
    c8: 20.0   # Invalid action penalty

  # Vessel generation
  vessel_generation:
    mode: realistic  # 'realistic' or 'simple'
    peak_hours: [6, 12, 18]  # Peak arrival hours
    peak_rate: 2.0  # Arrival rate multiplier during peak
    size_distribution: [0.3, 0.5, 0.2]  # [small, medium, large]
    shore_power_ratio: 0.6  # Ratio of vessels with shore power capability

# Agent configuration (MATD3)
agent:
  obs_dim: 17
  action_dim: 3
  num_agents: 20  # Should match max_vessels

  # Network architecture
  actor_hidden: [256, 256]
  critic_hidden: [512, 512, 256]

  # Learning rates
  actor_lr: 0.0001  # 1e-4
  critic_lr: 0.001   # 1e-3

  # RL hyperparameters
  gamma: 0.99
  tau: 0.005
  policy_delay: 2
  policy_noise: 0.2
  noise_clip: 0.5
  grad_clip: 1.0

  # Exploration noise
  exploration_noise:
    position: 0.1    # Std for position (normalized)
    time: 0.1        # Std for time (normalized)
    probability: 0.1 # Std for shore power probability

# Training configuration
training:
  num_episodes: 5000
  max_episode_steps: 1000
  batch_size: 256
  buffer_size: 1000000

  # Logging and evaluation
  eval_interval: 100  # Evaluate every N episodes
  eval_episodes: 10   # Number of episodes for evaluation
  save_interval: 100  # Save model every N episodes
  log_interval: 10    # Log metrics every N episodes

  # Paths
  save_dir: results/models
  log_dir: results/logs
  figure_dir: results/figures

# Evaluation configuration
evaluation:
  num_episodes: 100
  render: false
  save_allocations: true

# Random seed
seed: 42

# Device
device: cpu  # 'cpu' or 'cuda'
